### ISSUE TITLE
Error: This component must be used inside a <RecoilRoot> component.

### ISSUE THREAD

**Issue by AkifumiSato** [recruit-tech/recoil-sync-next#2]
I tried to develop with `yarn add link:<local path>` and got the following error

```
Server Error
Error: This component must be used inside a <RecoilRoot> component.
```

It seems to be related to the following issue, but I tried it with `reac@17` and `recoil@0.7.2` and got an error.
https://github.com/facebookexperimental/Recoil/issues/1802

**Comment by koichik** [comment]
Probably it is caused by a conflict between two Recoil packages.

* `<app>/node_modules/recoil`
* `<recoil-sync-next>/node_modules/recoil`

Can you try the following steps?

```bash
cd <app>
yarn unlink recoil-sync-next

cd <recoil-sync-next>
yarn unlink
yarn pack

cd <app>/node-modules
tar zxf <recoil-sync-next>/recoil-sync-next-v0.0.0.tgz
mv package recoil-sync-next
cd ..
yarn dev
```

**Comment by AkifumiSato** [comment]
Thanks, It worked!
l close this issue.
