### ISSUE TITLE
Would be great to have more clear examples

### ISSUE THREAD

**Issue by seleckis** [recruit-tech/recoil-sync-next#216]
I would like to ask for more clear examples of how to use this lib with nextjs. Let's imagine I have pages with dynamic routes:
```
[category]
> [post]
> > index.ts
```
And urls like: `/my-category/new-post`

I have tried to add atom like this:
```
export const categoryState = atom<string>({
  key: "category",
  default: "",
  effects: [syncEffect({ refine: string() })],
});
```
But 
```
const category = useRecoilValue(categoryState);
```
returns default value. As well as in selectors these atoms return default value. Any suggestion?

**Comment by koichik** [comment]
@seleckis I'm not sure what you mean, so could you explain the actual use case in more detail?

Because recoil-sync-next is just a Next.js binding for recoil-sync, therefore you can read the docs for recoil-sync, especialy the `location` option of `<RecoilURLSync />`.
https://recoiljs.org/docs/recoil-sync/api/RecoilURLSync#url-location

If you want to read/write segments of dynamic routes, unfortunately I don't think `<RecoilURLSync />` supports that functionality.

**Comment by seleckis** [comment]
I expect that library of name `recoil-sync-next` with component `RecoilURLSync` is suited to sync url data stored in next router with recoil store. If this is not so, could this be a feature request?

**Comment by koichik** [comment]
recoil-sync-next is, as the name suggests, a binding of recoil-sync ( especially `<RecoilURLSync />`) to Next.js.
Therefore, if you want `<RecoilURLSync />` to support URLs like the next/router segments, you should request it to Recoil first.

However, I don't think it would be useful.
So (again) could you please describe your specific use case?

**Comment by seleckis** [comment]
Well my case is to have actual dynamic route values available in selectors. It is impossible to use hook `useRouter` in selectors and atoms. I need to filter data depending on segments and make it available from selectors.

**Comment by koichik** [comment]
Ah, I see...
`<RecoilURLSync/>` is bidirectional, but probably what you want is just a unidirectional view of the next/router?
If so, using the raw Atom Effect instead of `<RecoilURLSync/>` for example:

```typescript
import Router from 'next/router'
import { atom, useRecoilValue } from 'recoil'

const nextRouterState = atom<typeof Router.query | null>({
  key: 'next/router',
  default: null,
  effects: [
    ({ setSelf }) => {
      if (typeof window !== 'undefined') {
        setSelf(Router.query)
        const handler = () => {
          setSelf(Router.query)
        }
        Router.events.on('routeChangeComplete', handler)
        return () => Router.events.off('routeChangeComplete', handler)
      }
    },
  ],
})

const MyComponent: React.FC = () => {
  const  = useRecoilValue(nextRouterState)
  ...
}
```

I'm not considering edge cases, but wouldn't that be a starting point?

**Comment by seleckis** [comment]
Thank you, will try your solution

**Comment by koichik** [comment]
Closing.
@seleckis If you still have problems, feel free to re-open this!
