### ISSUE TITLE
Support for Next 14+

### ISSUE THREAD

**Issue by tomrom-pomelo** [recruit-tech/recoil-sync-next#620]
Hi all - currently this package is pinned on Next < 14, but many other packages in our dependency list require 14+. For now, we have manually overwritten this requirement, but it would be great if this recoil-sync-next's deps could be updated! From our testing, it seems as though next `14.0.4` is fully compatible.

**Comment by AkifumiSato** [comment]
[v0.0.6](https://github.com/recruit-tech/recoil-sync-next/releases/tag/v0.0.6) is out!
It is now available in Next.js@v14.

**Comment by AkifumiSato** [comment]
Since `recoil` development has stalled, we have developed a new package `location-state`.
https://www.npmjs.com/package/@location-state/core
This one is also designed to be simpler with a state management library that synchronizes to history location. You can use this package too if you like.
